# Generated by Django 5.2.9 on 2026-02-16 09:52

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullName', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TOURIST', 'Tourist'), ('GUIDE', 'Guide')], default='TOURIST', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='tour_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='tour_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licenseNumber', models.CharField(default='PENDING-001', help_text='Official guide license number (format varies in Nepal)', max_length=100, unique=True)),
                ('licenseIssuedBy', models.CharField(default='Nepal Tourism Board', help_text='e.g. Nepal Tourism Board', max_length=150)),
                ('verificationStatus', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short introduction for Users and admins')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('reset_password', 'Reset Password'), ('registration', 'Registration Verification')], default='reset_password', max_length=20)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiresAt', models.DateTimeField()),
                ('isUsed', models.BooleanField(default=False)),
                ('reset_token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('reset_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_otp',
            },
        ),
    ]
