# Generated by Django 5.2.9 on 2026-02-09 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullName', models.CharField(max_length=150)),
                ('photo', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('TOURIST', 'Tourist'), ('GUIDE', 'Guide'), ('ADMIN', 'Admin')], max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
