# Generated by Django 5.2.9 on 2026-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Full address including city, district, country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Full address including city, district, country', max_length=255, null=True),
        ),
    ]
