# Generated by Django 5.2.9 on 2026-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_guideprofile_address_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo — stored in MEDIA_ROOT/profile_photos/', null=True, upload_to='profile_photos/'),
        ),
    ]
