# Generated by Django 5.2.9 on 2026-04-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='licenseNumber',
            field=models.CharField(blank=True, help_text='Official guide license number (format varies in Nepal)', max_length=100, null=True, unique=True),
        ),
    ]
