# Generated by Django 5.2.9 on 2026-02-22 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centerLatitude', models.FloatField()),
                ('centerLongitude', models.FloatField()),
                ('topKeywords', models.JSONField(default=list)),
                ('confidenceScore', models.FloatField(default=0.0)),
                ('dominantCategory', models.CharField(blank=True, max_length=100)),
                ('isAlertTriggered', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50)),
                ('triggerType', models.CharField(choices=[('MANUAL', 'Manual by Admin'), ('AUTO', 'Auto by Algorithm')], default='MANUAL', max_length=20)),
                ('broadcastTime', models.DateTimeField(auto_now_add=True)),
                ('broadcastedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcastedAlerts', to=settings.AUTH_USER_MODEL)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='reports.incidentcluster')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WEATHER', 'Weather'), ('LANDSLIDE', 'Landslide'), ('FLOOD', 'Flood'), ('ROAD_BLOCK', 'Road Block'), ('MEDICAL', 'Medical Emergency'), ('WILDLIFE', 'Wildlife'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='incident_images/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('confidenceScore', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('AUTO_ALERTED', 'Auto Alerted')], default='PENDING', max_length=20)),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentReports', to=settings.AUTH_USER_MODEL)),
                ('verifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifiedReports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incidentcluster',
            name='reports',
            field=models.ManyToManyField(related_name='cluster', to='reports.incidentreport'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notificationType', models.CharField(choices=[('NEW_INCIDENT', 'New Incident Reported'), ('CLUSTER_FORMED', 'Cluster Formed - Review Needed'), ('ALERT_BROADCAST', 'Alert Broadcasted'), ('REPORT_VERIFIED', 'Your Report Was Verified'), ('REPORT_REJECTED', 'Your Report Was Rejected'), ('AUTO_ALERT', 'Auto Alert Triggered')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('incidentReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.incidentreport')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
