# Generated by Django 5.2.9 on 2026-03-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='image',
            field=models.ImageField(upload_to='incident_images/'),
        ),
    ]
