# Generated by Django 5.2.9 on 2026-02-21 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertbroadcast',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='destination',
        ),
        migrations.AddField(
            model_name='alertbroadcast',
            name='broadcastedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcastedAlerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertbroadcast',
            name='triggerType',
            field=models.CharField(choices=[('MANUAL', 'Manual by Admin'), ('AUTO', 'Auto by Algorithm')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='confidenceScore',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='rejectionReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertbroadcast',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alertbroadcast',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('WEATHER', 'Weather'), ('LANDSLIDE', 'Landslide'), ('FLOOD', 'Flood'), ('ROAD_BLOCK', 'Road Block'), ('MEDICAL', 'Medical Emergency'), ('WILDLIFE', 'Wildlife'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('AUTO_ALERTED', 'Auto Alerted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentReports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IncidentCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centerLatitude', models.FloatField()),
                ('centerLongitude', models.FloatField()),
                ('topKeywords', models.JSONField(default=list)),
                ('confidenceScore', models.FloatField(default=0.0)),
                ('dominantCategory', models.CharField(blank=True, max_length=100)),
                ('isAlertTriggered', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('reports', models.ManyToManyField(related_name='cluster', to='reports.incidentreport')),
            ],
        ),
        migrations.AddField(
            model_name='alertbroadcast',
            name='cluster',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='reports.incidentcluster'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notificationType', models.CharField(choices=[('NEW_INCIDENT', 'New Incident Reported'), ('CLUSTER_FORMED', 'Cluster Formed - Review Needed'), ('ALERT_BROADCAST', 'Alert Broadcasted'), ('REPORT_VERIFIED', 'Your Report Was Verified'), ('REPORT_REJECTED', 'Your Report Was Rejected'), ('AUTO_ALERT', 'Auto Alert Triggered')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('incidentReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.incidentreport')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
