# Generated by Django 5.2.9 on 2026-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_comment_likedby_post_likedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('guides_only', 'Guides Only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
