# Generated by Django 5.2.9 on 2026-02-16 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('averageCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty', models.CharField(max_length=50)),
                ('bestSeason', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('famousLocalItems', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('climate', models.CharField(blank=True, max_length=100, null=True)),
                ('safetyLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('permitsRequired', models.BooleanField(default=False)),
                ('crowdLevel', models.CharField(max_length=50)),
                ('internetAvailability', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
