# Generated by Django 5.2.9 on 2026-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.URLField(blank=True, help_text='URL to a cover image of this destination', max_length=500, null=True),
        ),
    ]
