# Generated by Django 5.2.9 on 2026-03-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
    ]
