# Generated by Django 5.2.9 on 2026-03-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_city_destination_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='city',
            new_name='district',
        ),
    ]
