# Generated by Django 5.2.9 on 2026-02-09 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullName', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('TOURIST', 'Tourist'), ('GUIDE', 'Guide'), ('ADMIN', 'Admin')], max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('documentId', models.CharField(max_length=100)),
                ('verificationStatus', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guideProfile', to='profiles.user')),
            ],
        ),
    ]
